# Usa la imagen oficial de Node.js
FROM node:16

# Configura el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el package.json y package-lock.json al contenedor
COPY package*.json ./

# Instala las dependencias necesarias
RUN npm install

# Copia el código fuente de la aplicación al contenedor
COPY . .

# Expón el puerto 3000 donde tu aplicación escuchará
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["node", "main.js"]