#version: '3.8'

services:
  nessus-controller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nessus-controller
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network
    
  express-backend:
    build:
      context: ./path-to-express-backend
      dockerfile: Dockerfile-express
    container_name: express-backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nessus:
    image: tenable/nessus:${VERSION_OS}
    platform: linux/amd64
    restart: always
    container_name: nessus
    environment:
      USERNAME: ${NESSUS_USERNAME}         
      PASSWORD: ${NESSUS_PASSWORD}
      ACTIVATION_CODE: ${NESSUS_ACTIVATION_CODE}
    ports:
      - "8834:8834"
    networks:
      - app-network
    mem_limit: 8g  
    cpus: 4
    volumes:
      - nessus_data:/var/lib/nessus/data

volumes:
  postgres_data:
  nessus_data:

networks:
  app-network: