FROM node:16

# Configurar el directorio de trabajo
WORKDIR /app

# Copiar únicamente package.json y package-lock.json (optimización de cache)
COPY package.json package-lock.json ./

# Borra la carpeta node_modules (en caso de que exista)
RUN rm -rf node_modules

# Instala las dependencias de nuevo
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Ejecutar Prisma y exponer el puerto
RUN npx prisma generate
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["node", "main.js"]
